# Generated by Django 5.0.6 on 2025-04-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                ("user_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("hash_password", models.CharField(max_length=55)),
                ("role", models.CharField(max_length=50)),
            ],
        ),
    ]
