# Generated by Django 5.0.6 on 2025-05-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookiverse", "0002_rename_user_name_users_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="Flight",
            fields=[
                ("flight_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("flight_name", models.CharField(max_length=50)),
                ("plane_name", models.CharField(max_length=50)),
                ("flight_origin", models.CharField(max_length=50)),
                ("flight_departure", models.CharField(max_length=50)),
                ("flight_date", models.DateTimeField()),
                ("flight_price", models.IntegerField()),
                ("company", models.CharField(max_length=50)),
            ],
        ),
    ]
