# Generated by Django 5.0.3 on 2025-05-08 09:48

import bookiverse.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookiverse", "0003_flight"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hotel",
            fields=[
                ("hotel_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "hotel_name",
                    models.CharField(
                        error_messages={
                            "max_length": "Username too long (max 30 chars)",
                            "required": "You must choose a username",
                        },
                        max_length=30,
                        validators=[bookiverse.models.spacechecker],
                    ),
                ),
                (
                    "hotel_rooms",
                    models.CharField(
                        choices=[
                            ("1", "1 rooms"),
                            ("2", "2 rooms"),
                            ("3", "3 rooms"),
                            ("4", "4 rooms"),
                            ("suite", "suite"),
                        ],
                        max_length=30,
                    ),
                ),
                ("hotel_price", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="users",
            name="flight",
            field=models.ManyToManyField(
                related_name="flights", to="bookiverse.flight"
            ),
        ),
    ]
